language: python
sudo: false
python:
- 3.4

install:
- pip install -r requirements.txt
- gem install sass

script:
- make publish

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
  - OUTPUTDIR: output
  - GH_REF: github.com/pydelhi/blog.git
  - secure: "xUV95cXVwzxeM/lW32z7HDykQrJa6F3D45Pr9CHeawKeZsoJ4QKI1hSyywAL/jFvaxGCUvCoVhN2U+goO293UP37p/WroNfKTLYf0afLB2WJJe0pb7dDOzKvF8qAGt9pkc6BdSGHQGlMQn26jXCb11LUkjKlysyMEEIb6EH9hl8VzhtQwxwlWHEIjmbzwYCRl+ZgieO8L7epJBRDiPwkaVYuz8EFXobDwks/YfXBRSzAAXS/dm6qMJgwg+zf3n6ZCyjGLhPu9B1/qol3W578EA0JcWznGN4ZWDQmCVDRptAbnDCrBh41WjKzZg+QmI8ixzr43UZiqyLtjglCR7YBf5k0rn/6MhOvlJQStoT19SCqnK1fbXh6zlJkpsIrhSeaRd3T1ULAT5FlhA1mghBTuNeeLt0Y9lAAlX+zQxFsYhzVjHc1nNA9GmJj55fVpGWjGg0BolAzDjRG7GglbMBjxupAmsvsooZn5jUI4EmBDTIOrz72iXN/oTPqHnTmhfoRD6qoSaZgX389vA1qX5wfwSc/YcMClEHPHdqIHzvMXOrzkFxU7Jdlx1uiJmdZ17uQbR6FdWU4I3rKN7Cjuv9aQoH34aOvTmI5Ol4LVbBkhERxXvZiUPyj1zOOfGK6nkh6iCGZG5yYfDXFoQXddt2nTw09v25mm+la2D+NyxjRQO0="
after_success:
- ghp-import ${OUTPUTDIR} -m "Blog updated with travis"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
