language: python
sudo: false
python:
- 3.4

install:
- pip install -r requirements.txt
- gem install sass

script:
- make publish

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
  - OUTPUTDIR: output
  - GH_REF: github.com/pydelhi/blog.git
  - secure: "nqOw3HH0qjFybFTekev6LO0DSh/TMZoIsae0fIaG6qF1sU4+2EkDZgj2lTfaIVN/EIuhuPrzEJuNL+Jrm1T9olss2g+V+rBcBTIJKkrkAztmjErA9+gi3AmG8jI9Hh+9Z6AURY+Plogf4Hgv6O4oog5LXZZMIG+5twR0elK3zU3EW4Htgq9xNx/fCQm4K2Hlta5AcrQc0MXzf0eZ9LNTENQ1GUqMAvzMtNjBQqAs/mHfcrLo/28W2e6q2dxkHMNNJAfYCgKvC2+VpJgh0eFqXT+EgwCZ7CWNmiMP0SHfdNjZsgQrkWmht6xC9c9moGTvH18g3C3Xjw/6OJuaL1RYnDIk2svfRf+7WVcPJ8F9YDIFTbNjrS7MOLWcOnVNI5Ngiz7o41vBJ2JhI7ef533WZACai7gZL1uGIw54jkIwZgAetHTETJM5j5OZZaw8WbPn0Ey1sgpgNsO0b3m2D8GSD5NLyEjp8Nhv6zdhYRUiVhoS274L76QsH24+ZFCD5nUxCDeS5KB74hqYpra44jHJNkFKMEQytTR3rKvBLcn/14cxf+HMRbSEedxV5IHNmVmCN/AELs6nE0pY1djOM9kKFQCU/L/JHfKTcdiTtih9W38EeKya6cPs+CERbN+EwiXzGVVOE7E/5ZJryTgM3r6EpfM7j9DWaWlIZJtvTt1DbFc="
after_success:
- ghp-import ${OUTPUTDIR} -m "Blog updated with travis"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
